apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage.fullname" . }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: backend
  selector:
    {{- include "backstage.selectorLabels" . | nindent 4 }}
